//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace myshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class feed
    {
        public int feedid { get; set; }
        [Required(ErrorMessage = "Please Enter"), MaxLength(150)]
        public string feedq { get; set; }
        [Required(ErrorMessage = "Please Enter"), MaxLength(150)]
        public string feeda { get; set; }
    }
}
