//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace myshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblorder()
        {
            this.tblorderdetails = new HashSet<tblorderdetail>();
        }
    
        public int oid { get; set; }
        public System.DateTime odate { get; set; }
        [Required(ErrorMessage = "Cant be empty")]
        public string opname { get; set; }
        [Required(ErrorMessage = "Cant be empty")]
        public string opphone { get; set; }
        [Required(ErrorMessage = "Cant be empty")]
        public string opaddress { get; set; }
        [Required(ErrorMessage = "Cant be empty")]
        public decimal oamount { get; set; }
        [Required(ErrorMessage = "Cant be empty")]
        public int ostatus { get; set; }
    
        public virtual tblcust tblcust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorderdetail> tblorderdetails { get; set; }
    }
}
